//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Plugins/BearFramework/BearCharacter/Runtime/Inputs/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""0e1e2564-8fea-4a7f-9172-0b9d66413748"",
            ""actions"": [
                {
                    ""name"": ""MoveDir"",
                    ""type"": ""PassThrough"",
                    ""id"": ""18aed459-b1aa-4ecd-b643-17d1dce82339"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ClickOnTarget"",
                    ""type"": ""Button"",
                    ""id"": ""f3f442c9-6b93-47b6-8b3a-7c098dda4195"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""27279a1a-a14d-4d4f-9e27-54aad547f1fb"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveDir"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c0dc9464-e07b-4ea1-8147-d28021051dfc"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveDir"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b711ea07-85e7-491c-81ff-cf368274858f"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveDir"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""14f917e0-5592-46f5-b757-d55375d6043f"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveDir"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""9a288e27-e1f3-4020-8537-8877297aaf4c"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveDir"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""bb123154-e751-45f5-a976-c636756a04b8"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveDir"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9e16002f-cf8f-40c7-b80b-01483c756585"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveDir"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""4c817756-ca95-4787-98a9-63707d52e844"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveDir"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""0011d5cc-608a-4712-9977-3211452ab379"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveDir"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""27e8ce4a-8e29-48b2-b9d8-417bdc1e6fec"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveDir"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""40c7a335-dfdd-41e0-bfba-ac45f57a0ab9"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClickOnTarget"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""ShortCut"",
            ""id"": ""0c9eda45-5808-43f0-91db-bd003c084217"",
            ""actions"": [
                {
                    ""name"": ""ShortCut1"",
                    ""type"": ""Button"",
                    ""id"": ""24f06d9e-cc1b-4aaf-8dcc-540cff320e37"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShortCut2"",
                    ""type"": ""Button"",
                    ""id"": ""25093205-a287-4f4a-bef6-ae5c60af6139"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShortCut3"",
                    ""type"": ""Button"",
                    ""id"": ""20963364-16e7-47dd-bef1-0e62850a30e5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShortCut4"",
                    ""type"": ""Button"",
                    ""id"": ""24d66932-8f90-49fa-a2f6-9acb7d0bac90"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShortCut5"",
                    ""type"": ""Button"",
                    ""id"": ""c86ac359-3445-498f-a79c-2b3cd4fe2743"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShortCut6"",
                    ""type"": ""Button"",
                    ""id"": ""47c878b0-d450-49ef-8fa0-0bd0a1829640"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c76934ed-5b8b-40a4-a999-7033ed9e4c7a"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortCut1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a1edfae1-752f-44d2-8d1b-f0a7b89397c3"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortCut2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""181fc822-637e-4ae1-9741-1fe1f99ec511"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortCut3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""389e166d-ee4d-473a-9482-bcbb9f1a9023"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortCut4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ee0e421b-dfab-4258-a53f-d4b10c5cd068"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortCut5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7cd396b8-a9a1-4e08-8954-46e0a76f77a6"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortCut6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""63abdf59-63c3-4675-a23c-9c2648e5b1ba"",
            ""actions"": [
                {
                    ""name"": ""UIShortCut6"",
                    ""type"": ""Button"",
                    ""id"": ""a53210a3-d3eb-44b3-9cc3-0848d78dc5c3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UIShortCut5"",
                    ""type"": ""Button"",
                    ""id"": ""bdf51996-2925-4f9c-9cd2-c2a43d33c25e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UIShortCut4"",
                    ""type"": ""Button"",
                    ""id"": ""9886bc7a-abab-428d-a6d8-4dfc2e45fd57"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UIShortCut3"",
                    ""type"": ""Button"",
                    ""id"": ""003e9133-88da-4e32-9e97-fc261f98f4cf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UIShortCut2"",
                    ""type"": ""Button"",
                    ""id"": ""4def82ae-9d1d-4dd0-98de-ab59cf6e4c38"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UIShortCut1"",
                    ""type"": ""Button"",
                    ""id"": ""17d37898-bf61-4e0a-8e68-57315b0ba551"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""208da6f5-f689-4b07-97bc-55d89cab6cf8"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UIShortCut1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""56b415a5-1ca5-403d-a466-dcd06d3637ee"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UIShortCut2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9175c22d-b485-4fd8-b815-3b1d58bc2f71"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UIShortCut3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bb2911b4-c6f3-4ea3-b744-4e7e7ee8081f"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UIShortCut4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0dc10e15-b471-4aae-992f-c3ec74e7e472"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UIShortCut5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c41041d-057b-4da6-9e91-1e40b1284727"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UIShortCut6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Camera"",
            ""id"": ""64dcf2d1-0591-40e5-8cd2-5e6c937720e3"",
            ""actions"": [
                {
                    ""name"": ""CameraXY"",
                    ""type"": ""Value"",
                    ""id"": ""3c4ed53f-97c0-4fb8-886c-279af5310976"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraZoom"",
                    ""type"": ""Value"",
                    ""id"": ""ad730095-225f-46ff-a762-b7546d6ce724"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""cfe3df62-f100-4f69-8b58-878cd8c93d9b"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraXY"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""32f8a645-d24a-4eb6-a270-28f89ddf901e"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraXY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""46c28503-5d17-40b9-9ea2-04e897b12cb2"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraXY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""5b9f0ee8-d042-43a8-b429-46762f35e60a"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraZoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Misc"",
            ""id"": ""d7f13bd2-4bf7-4412-8b89-e0a99b95946a"",
            ""actions"": [
                {
                    ""name"": ""SpeedUp"",
                    ""type"": ""PassThrough"",
                    ""id"": ""424873e9-5431-46c3-82a3-aae72a70f787"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a71c0e3c-8919-4631-aabd-5eedebabbb0e"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpeedUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Move"",
            ""id"": ""f2d6094b-5abe-4a46-86f1-5b2225a0a705"",
            ""actions"": [
                {
                    ""name"": ""Roll"",
                    ""type"": ""Button"",
                    ""id"": ""13c373dd-c8e9-429b-9afe-628bfd4ad095"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""5e8a56ad-74c7-48c7-b8b1-cff975bd9075"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""99466da6-b6c9-44c3-a000-7dd8da675b44"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Roll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e38cf42b-3c2f-406b-835b-196c660d09a2"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Item"",
            ""id"": ""6826a2dc-e4da-4668-b4fc-5a22030cecf3"",
            ""actions"": [
                {
                    ""name"": ""RBT"",
                    ""type"": ""Button"",
                    ""id"": ""38283d75-4240-4af1-a420-01946e8402ef"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RBH"",
                    ""type"": ""Button"",
                    ""id"": ""66f4d8ab-29e1-4630-be1f-2ee54e758359"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RTT"",
                    ""type"": ""Button"",
                    ""id"": ""57cf295c-20bc-493b-ba7e-3d271129e5d0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RTH"",
                    ""type"": ""Button"",
                    ""id"": ""dfc6c440-c22d-42dc-a4ee-68cbf10d303c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LBT"",
                    ""type"": ""Button"",
                    ""id"": ""a73d680e-b191-4379-9576-2689ecad2939"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LBH"",
                    ""type"": ""Button"",
                    ""id"": ""e3dcf869-fa1e-4095-a805-32eb5fe8d765"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LTT"",
                    ""type"": ""Button"",
                    ""id"": ""da982a60-17d3-4cef-be8c-9d5902541b46"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LTH"",
                    ""type"": ""Button"",
                    ""id"": ""a81dbce5-5d47-42e4-91cd-249cabbefe00"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""364f1a28-b6ca-4b1e-b409-853443546cc1"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RBT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0e599ae1-3668-4303-bd6b-fc10cf942696"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RBH"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""72485244-1956-42ee-a6c1-ccea04328940"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RTT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e509afdc-32d1-4123-aaa9-79ca070b920c"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RTH"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4c711ae9-e71a-4c3f-8568-85228448bf6c"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LBT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5d01032d-3573-4bae-96e6-7955a0f7aeb7"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LBH"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4932e92a-474a-47e5-8db3-acc937b016df"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LTT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8357f955-dfcf-4a82-818d-774c7311d25a"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LTH"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_MoveDir = m_Player.FindAction("MoveDir", throwIfNotFound: true);
        m_Player_ClickOnTarget = m_Player.FindAction("ClickOnTarget", throwIfNotFound: true);
        // ShortCut
        m_ShortCut = asset.FindActionMap("ShortCut", throwIfNotFound: true);
        m_ShortCut_ShortCut1 = m_ShortCut.FindAction("ShortCut1", throwIfNotFound: true);
        m_ShortCut_ShortCut2 = m_ShortCut.FindAction("ShortCut2", throwIfNotFound: true);
        m_ShortCut_ShortCut3 = m_ShortCut.FindAction("ShortCut3", throwIfNotFound: true);
        m_ShortCut_ShortCut4 = m_ShortCut.FindAction("ShortCut4", throwIfNotFound: true);
        m_ShortCut_ShortCut5 = m_ShortCut.FindAction("ShortCut5", throwIfNotFound: true);
        m_ShortCut_ShortCut6 = m_ShortCut.FindAction("ShortCut6", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_UIShortCut6 = m_UI.FindAction("UIShortCut6", throwIfNotFound: true);
        m_UI_UIShortCut5 = m_UI.FindAction("UIShortCut5", throwIfNotFound: true);
        m_UI_UIShortCut4 = m_UI.FindAction("UIShortCut4", throwIfNotFound: true);
        m_UI_UIShortCut3 = m_UI.FindAction("UIShortCut3", throwIfNotFound: true);
        m_UI_UIShortCut2 = m_UI.FindAction("UIShortCut2", throwIfNotFound: true);
        m_UI_UIShortCut1 = m_UI.FindAction("UIShortCut1", throwIfNotFound: true);
        // Camera
        m_Camera = asset.FindActionMap("Camera", throwIfNotFound: true);
        m_Camera_CameraXY = m_Camera.FindAction("CameraXY", throwIfNotFound: true);
        m_Camera_CameraZoom = m_Camera.FindAction("CameraZoom", throwIfNotFound: true);
        // Misc
        m_Misc = asset.FindActionMap("Misc", throwIfNotFound: true);
        m_Misc_SpeedUp = m_Misc.FindAction("SpeedUp", throwIfNotFound: true);
        // Move
        m_Move = asset.FindActionMap("Move", throwIfNotFound: true);
        m_Move_Roll = m_Move.FindAction("Roll", throwIfNotFound: true);
        m_Move_Jump = m_Move.FindAction("Jump", throwIfNotFound: true);
        // Item
        m_Item = asset.FindActionMap("Item", throwIfNotFound: true);
        m_Item_RBT = m_Item.FindAction("RBT", throwIfNotFound: true);
        m_Item_RBH = m_Item.FindAction("RBH", throwIfNotFound: true);
        m_Item_RTT = m_Item.FindAction("RTT", throwIfNotFound: true);
        m_Item_RTH = m_Item.FindAction("RTH", throwIfNotFound: true);
        m_Item_LBT = m_Item.FindAction("LBT", throwIfNotFound: true);
        m_Item_LBH = m_Item.FindAction("LBH", throwIfNotFound: true);
        m_Item_LTT = m_Item.FindAction("LTT", throwIfNotFound: true);
        m_Item_LTH = m_Item.FindAction("LTH", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_MoveDir;
    private readonly InputAction m_Player_ClickOnTarget;
    public struct PlayerActions
    {
        private @PlayerInput m_Wrapper;
        public PlayerActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @MoveDir => m_Wrapper.m_Player_MoveDir;
        public InputAction @ClickOnTarget => m_Wrapper.m_Player_ClickOnTarget;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @MoveDir.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMoveDir;
                @MoveDir.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMoveDir;
                @MoveDir.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMoveDir;
                @ClickOnTarget.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnClickOnTarget;
                @ClickOnTarget.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnClickOnTarget;
                @ClickOnTarget.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnClickOnTarget;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MoveDir.started += instance.OnMoveDir;
                @MoveDir.performed += instance.OnMoveDir;
                @MoveDir.canceled += instance.OnMoveDir;
                @ClickOnTarget.started += instance.OnClickOnTarget;
                @ClickOnTarget.performed += instance.OnClickOnTarget;
                @ClickOnTarget.canceled += instance.OnClickOnTarget;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // ShortCut
    private readonly InputActionMap m_ShortCut;
    private IShortCutActions m_ShortCutActionsCallbackInterface;
    private readonly InputAction m_ShortCut_ShortCut1;
    private readonly InputAction m_ShortCut_ShortCut2;
    private readonly InputAction m_ShortCut_ShortCut3;
    private readonly InputAction m_ShortCut_ShortCut4;
    private readonly InputAction m_ShortCut_ShortCut5;
    private readonly InputAction m_ShortCut_ShortCut6;
    public struct ShortCutActions
    {
        private @PlayerInput m_Wrapper;
        public ShortCutActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @ShortCut1 => m_Wrapper.m_ShortCut_ShortCut1;
        public InputAction @ShortCut2 => m_Wrapper.m_ShortCut_ShortCut2;
        public InputAction @ShortCut3 => m_Wrapper.m_ShortCut_ShortCut3;
        public InputAction @ShortCut4 => m_Wrapper.m_ShortCut_ShortCut4;
        public InputAction @ShortCut5 => m_Wrapper.m_ShortCut_ShortCut5;
        public InputAction @ShortCut6 => m_Wrapper.m_ShortCut_ShortCut6;
        public InputActionMap Get() { return m_Wrapper.m_ShortCut; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ShortCutActions set) { return set.Get(); }
        public void SetCallbacks(IShortCutActions instance)
        {
            if (m_Wrapper.m_ShortCutActionsCallbackInterface != null)
            {
                @ShortCut1.started -= m_Wrapper.m_ShortCutActionsCallbackInterface.OnShortCut1;
                @ShortCut1.performed -= m_Wrapper.m_ShortCutActionsCallbackInterface.OnShortCut1;
                @ShortCut1.canceled -= m_Wrapper.m_ShortCutActionsCallbackInterface.OnShortCut1;
                @ShortCut2.started -= m_Wrapper.m_ShortCutActionsCallbackInterface.OnShortCut2;
                @ShortCut2.performed -= m_Wrapper.m_ShortCutActionsCallbackInterface.OnShortCut2;
                @ShortCut2.canceled -= m_Wrapper.m_ShortCutActionsCallbackInterface.OnShortCut2;
                @ShortCut3.started -= m_Wrapper.m_ShortCutActionsCallbackInterface.OnShortCut3;
                @ShortCut3.performed -= m_Wrapper.m_ShortCutActionsCallbackInterface.OnShortCut3;
                @ShortCut3.canceled -= m_Wrapper.m_ShortCutActionsCallbackInterface.OnShortCut3;
                @ShortCut4.started -= m_Wrapper.m_ShortCutActionsCallbackInterface.OnShortCut4;
                @ShortCut4.performed -= m_Wrapper.m_ShortCutActionsCallbackInterface.OnShortCut4;
                @ShortCut4.canceled -= m_Wrapper.m_ShortCutActionsCallbackInterface.OnShortCut4;
                @ShortCut5.started -= m_Wrapper.m_ShortCutActionsCallbackInterface.OnShortCut5;
                @ShortCut5.performed -= m_Wrapper.m_ShortCutActionsCallbackInterface.OnShortCut5;
                @ShortCut5.canceled -= m_Wrapper.m_ShortCutActionsCallbackInterface.OnShortCut5;
                @ShortCut6.started -= m_Wrapper.m_ShortCutActionsCallbackInterface.OnShortCut6;
                @ShortCut6.performed -= m_Wrapper.m_ShortCutActionsCallbackInterface.OnShortCut6;
                @ShortCut6.canceled -= m_Wrapper.m_ShortCutActionsCallbackInterface.OnShortCut6;
            }
            m_Wrapper.m_ShortCutActionsCallbackInterface = instance;
            if (instance != null)
            {
                @ShortCut1.started += instance.OnShortCut1;
                @ShortCut1.performed += instance.OnShortCut1;
                @ShortCut1.canceled += instance.OnShortCut1;
                @ShortCut2.started += instance.OnShortCut2;
                @ShortCut2.performed += instance.OnShortCut2;
                @ShortCut2.canceled += instance.OnShortCut2;
                @ShortCut3.started += instance.OnShortCut3;
                @ShortCut3.performed += instance.OnShortCut3;
                @ShortCut3.canceled += instance.OnShortCut3;
                @ShortCut4.started += instance.OnShortCut4;
                @ShortCut4.performed += instance.OnShortCut4;
                @ShortCut4.canceled += instance.OnShortCut4;
                @ShortCut5.started += instance.OnShortCut5;
                @ShortCut5.performed += instance.OnShortCut5;
                @ShortCut5.canceled += instance.OnShortCut5;
                @ShortCut6.started += instance.OnShortCut6;
                @ShortCut6.performed += instance.OnShortCut6;
                @ShortCut6.canceled += instance.OnShortCut6;
            }
        }
    }
    public ShortCutActions @ShortCut => new ShortCutActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private IUIActions m_UIActionsCallbackInterface;
    private readonly InputAction m_UI_UIShortCut6;
    private readonly InputAction m_UI_UIShortCut5;
    private readonly InputAction m_UI_UIShortCut4;
    private readonly InputAction m_UI_UIShortCut3;
    private readonly InputAction m_UI_UIShortCut2;
    private readonly InputAction m_UI_UIShortCut1;
    public struct UIActions
    {
        private @PlayerInput m_Wrapper;
        public UIActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @UIShortCut6 => m_Wrapper.m_UI_UIShortCut6;
        public InputAction @UIShortCut5 => m_Wrapper.m_UI_UIShortCut5;
        public InputAction @UIShortCut4 => m_Wrapper.m_UI_UIShortCut4;
        public InputAction @UIShortCut3 => m_Wrapper.m_UI_UIShortCut3;
        public InputAction @UIShortCut2 => m_Wrapper.m_UI_UIShortCut2;
        public InputAction @UIShortCut1 => m_Wrapper.m_UI_UIShortCut1;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void SetCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterface != null)
            {
                @UIShortCut6.started -= m_Wrapper.m_UIActionsCallbackInterface.OnUIShortCut6;
                @UIShortCut6.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnUIShortCut6;
                @UIShortCut6.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnUIShortCut6;
                @UIShortCut5.started -= m_Wrapper.m_UIActionsCallbackInterface.OnUIShortCut5;
                @UIShortCut5.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnUIShortCut5;
                @UIShortCut5.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnUIShortCut5;
                @UIShortCut4.started -= m_Wrapper.m_UIActionsCallbackInterface.OnUIShortCut4;
                @UIShortCut4.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnUIShortCut4;
                @UIShortCut4.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnUIShortCut4;
                @UIShortCut3.started -= m_Wrapper.m_UIActionsCallbackInterface.OnUIShortCut3;
                @UIShortCut3.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnUIShortCut3;
                @UIShortCut3.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnUIShortCut3;
                @UIShortCut2.started -= m_Wrapper.m_UIActionsCallbackInterface.OnUIShortCut2;
                @UIShortCut2.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnUIShortCut2;
                @UIShortCut2.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnUIShortCut2;
                @UIShortCut1.started -= m_Wrapper.m_UIActionsCallbackInterface.OnUIShortCut1;
                @UIShortCut1.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnUIShortCut1;
                @UIShortCut1.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnUIShortCut1;
            }
            m_Wrapper.m_UIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @UIShortCut6.started += instance.OnUIShortCut6;
                @UIShortCut6.performed += instance.OnUIShortCut6;
                @UIShortCut6.canceled += instance.OnUIShortCut6;
                @UIShortCut5.started += instance.OnUIShortCut5;
                @UIShortCut5.performed += instance.OnUIShortCut5;
                @UIShortCut5.canceled += instance.OnUIShortCut5;
                @UIShortCut4.started += instance.OnUIShortCut4;
                @UIShortCut4.performed += instance.OnUIShortCut4;
                @UIShortCut4.canceled += instance.OnUIShortCut4;
                @UIShortCut3.started += instance.OnUIShortCut3;
                @UIShortCut3.performed += instance.OnUIShortCut3;
                @UIShortCut3.canceled += instance.OnUIShortCut3;
                @UIShortCut2.started += instance.OnUIShortCut2;
                @UIShortCut2.performed += instance.OnUIShortCut2;
                @UIShortCut2.canceled += instance.OnUIShortCut2;
                @UIShortCut1.started += instance.OnUIShortCut1;
                @UIShortCut1.performed += instance.OnUIShortCut1;
                @UIShortCut1.canceled += instance.OnUIShortCut1;
            }
        }
    }
    public UIActions @UI => new UIActions(this);

    // Camera
    private readonly InputActionMap m_Camera;
    private ICameraActions m_CameraActionsCallbackInterface;
    private readonly InputAction m_Camera_CameraXY;
    private readonly InputAction m_Camera_CameraZoom;
    public struct CameraActions
    {
        private @PlayerInput m_Wrapper;
        public CameraActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @CameraXY => m_Wrapper.m_Camera_CameraXY;
        public InputAction @CameraZoom => m_Wrapper.m_Camera_CameraZoom;
        public InputActionMap Get() { return m_Wrapper.m_Camera; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CameraActions set) { return set.Get(); }
        public void SetCallbacks(ICameraActions instance)
        {
            if (m_Wrapper.m_CameraActionsCallbackInterface != null)
            {
                @CameraXY.started -= m_Wrapper.m_CameraActionsCallbackInterface.OnCameraXY;
                @CameraXY.performed -= m_Wrapper.m_CameraActionsCallbackInterface.OnCameraXY;
                @CameraXY.canceled -= m_Wrapper.m_CameraActionsCallbackInterface.OnCameraXY;
                @CameraZoom.started -= m_Wrapper.m_CameraActionsCallbackInterface.OnCameraZoom;
                @CameraZoom.performed -= m_Wrapper.m_CameraActionsCallbackInterface.OnCameraZoom;
                @CameraZoom.canceled -= m_Wrapper.m_CameraActionsCallbackInterface.OnCameraZoom;
            }
            m_Wrapper.m_CameraActionsCallbackInterface = instance;
            if (instance != null)
            {
                @CameraXY.started += instance.OnCameraXY;
                @CameraXY.performed += instance.OnCameraXY;
                @CameraXY.canceled += instance.OnCameraXY;
                @CameraZoom.started += instance.OnCameraZoom;
                @CameraZoom.performed += instance.OnCameraZoom;
                @CameraZoom.canceled += instance.OnCameraZoom;
            }
        }
    }
    public CameraActions @Camera => new CameraActions(this);

    // Misc
    private readonly InputActionMap m_Misc;
    private IMiscActions m_MiscActionsCallbackInterface;
    private readonly InputAction m_Misc_SpeedUp;
    public struct MiscActions
    {
        private @PlayerInput m_Wrapper;
        public MiscActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @SpeedUp => m_Wrapper.m_Misc_SpeedUp;
        public InputActionMap Get() { return m_Wrapper.m_Misc; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MiscActions set) { return set.Get(); }
        public void SetCallbacks(IMiscActions instance)
        {
            if (m_Wrapper.m_MiscActionsCallbackInterface != null)
            {
                @SpeedUp.started -= m_Wrapper.m_MiscActionsCallbackInterface.OnSpeedUp;
                @SpeedUp.performed -= m_Wrapper.m_MiscActionsCallbackInterface.OnSpeedUp;
                @SpeedUp.canceled -= m_Wrapper.m_MiscActionsCallbackInterface.OnSpeedUp;
            }
            m_Wrapper.m_MiscActionsCallbackInterface = instance;
            if (instance != null)
            {
                @SpeedUp.started += instance.OnSpeedUp;
                @SpeedUp.performed += instance.OnSpeedUp;
                @SpeedUp.canceled += instance.OnSpeedUp;
            }
        }
    }
    public MiscActions @Misc => new MiscActions(this);

    // Move
    private readonly InputActionMap m_Move;
    private IMoveActions m_MoveActionsCallbackInterface;
    private readonly InputAction m_Move_Roll;
    private readonly InputAction m_Move_Jump;
    public struct MoveActions
    {
        private @PlayerInput m_Wrapper;
        public MoveActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Roll => m_Wrapper.m_Move_Roll;
        public InputAction @Jump => m_Wrapper.m_Move_Jump;
        public InputActionMap Get() { return m_Wrapper.m_Move; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MoveActions set) { return set.Get(); }
        public void SetCallbacks(IMoveActions instance)
        {
            if (m_Wrapper.m_MoveActionsCallbackInterface != null)
            {
                @Roll.started -= m_Wrapper.m_MoveActionsCallbackInterface.OnRoll;
                @Roll.performed -= m_Wrapper.m_MoveActionsCallbackInterface.OnRoll;
                @Roll.canceled -= m_Wrapper.m_MoveActionsCallbackInterface.OnRoll;
                @Jump.started -= m_Wrapper.m_MoveActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_MoveActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_MoveActionsCallbackInterface.OnJump;
            }
            m_Wrapper.m_MoveActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Roll.started += instance.OnRoll;
                @Roll.performed += instance.OnRoll;
                @Roll.canceled += instance.OnRoll;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
            }
        }
    }
    public MoveActions @Move => new MoveActions(this);

    // Item
    private readonly InputActionMap m_Item;
    private IItemActions m_ItemActionsCallbackInterface;
    private readonly InputAction m_Item_RBT;
    private readonly InputAction m_Item_RBH;
    private readonly InputAction m_Item_RTT;
    private readonly InputAction m_Item_RTH;
    private readonly InputAction m_Item_LBT;
    private readonly InputAction m_Item_LBH;
    private readonly InputAction m_Item_LTT;
    private readonly InputAction m_Item_LTH;
    public struct ItemActions
    {
        private @PlayerInput m_Wrapper;
        public ItemActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @RBT => m_Wrapper.m_Item_RBT;
        public InputAction @RBH => m_Wrapper.m_Item_RBH;
        public InputAction @RTT => m_Wrapper.m_Item_RTT;
        public InputAction @RTH => m_Wrapper.m_Item_RTH;
        public InputAction @LBT => m_Wrapper.m_Item_LBT;
        public InputAction @LBH => m_Wrapper.m_Item_LBH;
        public InputAction @LTT => m_Wrapper.m_Item_LTT;
        public InputAction @LTH => m_Wrapper.m_Item_LTH;
        public InputActionMap Get() { return m_Wrapper.m_Item; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ItemActions set) { return set.Get(); }
        public void SetCallbacks(IItemActions instance)
        {
            if (m_Wrapper.m_ItemActionsCallbackInterface != null)
            {
                @RBT.started -= m_Wrapper.m_ItemActionsCallbackInterface.OnRBT;
                @RBT.performed -= m_Wrapper.m_ItemActionsCallbackInterface.OnRBT;
                @RBT.canceled -= m_Wrapper.m_ItemActionsCallbackInterface.OnRBT;
                @RBH.started -= m_Wrapper.m_ItemActionsCallbackInterface.OnRBH;
                @RBH.performed -= m_Wrapper.m_ItemActionsCallbackInterface.OnRBH;
                @RBH.canceled -= m_Wrapper.m_ItemActionsCallbackInterface.OnRBH;
                @RTT.started -= m_Wrapper.m_ItemActionsCallbackInterface.OnRTT;
                @RTT.performed -= m_Wrapper.m_ItemActionsCallbackInterface.OnRTT;
                @RTT.canceled -= m_Wrapper.m_ItemActionsCallbackInterface.OnRTT;
                @RTH.started -= m_Wrapper.m_ItemActionsCallbackInterface.OnRTH;
                @RTH.performed -= m_Wrapper.m_ItemActionsCallbackInterface.OnRTH;
                @RTH.canceled -= m_Wrapper.m_ItemActionsCallbackInterface.OnRTH;
                @LBT.started -= m_Wrapper.m_ItemActionsCallbackInterface.OnLBT;
                @LBT.performed -= m_Wrapper.m_ItemActionsCallbackInterface.OnLBT;
                @LBT.canceled -= m_Wrapper.m_ItemActionsCallbackInterface.OnLBT;
                @LBH.started -= m_Wrapper.m_ItemActionsCallbackInterface.OnLBH;
                @LBH.performed -= m_Wrapper.m_ItemActionsCallbackInterface.OnLBH;
                @LBH.canceled -= m_Wrapper.m_ItemActionsCallbackInterface.OnLBH;
                @LTT.started -= m_Wrapper.m_ItemActionsCallbackInterface.OnLTT;
                @LTT.performed -= m_Wrapper.m_ItemActionsCallbackInterface.OnLTT;
                @LTT.canceled -= m_Wrapper.m_ItemActionsCallbackInterface.OnLTT;
                @LTH.started -= m_Wrapper.m_ItemActionsCallbackInterface.OnLTH;
                @LTH.performed -= m_Wrapper.m_ItemActionsCallbackInterface.OnLTH;
                @LTH.canceled -= m_Wrapper.m_ItemActionsCallbackInterface.OnLTH;
            }
            m_Wrapper.m_ItemActionsCallbackInterface = instance;
            if (instance != null)
            {
                @RBT.started += instance.OnRBT;
                @RBT.performed += instance.OnRBT;
                @RBT.canceled += instance.OnRBT;
                @RBH.started += instance.OnRBH;
                @RBH.performed += instance.OnRBH;
                @RBH.canceled += instance.OnRBH;
                @RTT.started += instance.OnRTT;
                @RTT.performed += instance.OnRTT;
                @RTT.canceled += instance.OnRTT;
                @RTH.started += instance.OnRTH;
                @RTH.performed += instance.OnRTH;
                @RTH.canceled += instance.OnRTH;
                @LBT.started += instance.OnLBT;
                @LBT.performed += instance.OnLBT;
                @LBT.canceled += instance.OnLBT;
                @LBH.started += instance.OnLBH;
                @LBH.performed += instance.OnLBH;
                @LBH.canceled += instance.OnLBH;
                @LTT.started += instance.OnLTT;
                @LTT.performed += instance.OnLTT;
                @LTT.canceled += instance.OnLTT;
                @LTH.started += instance.OnLTH;
                @LTH.performed += instance.OnLTH;
                @LTH.canceled += instance.OnLTH;
            }
        }
    }
    public ItemActions @Item => new ItemActions(this);
    public interface IPlayerActions
    {
        void OnMoveDir(InputAction.CallbackContext context);
        void OnClickOnTarget(InputAction.CallbackContext context);
    }
    public interface IShortCutActions
    {
        void OnShortCut1(InputAction.CallbackContext context);
        void OnShortCut2(InputAction.CallbackContext context);
        void OnShortCut3(InputAction.CallbackContext context);
        void OnShortCut4(InputAction.CallbackContext context);
        void OnShortCut5(InputAction.CallbackContext context);
        void OnShortCut6(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnUIShortCut6(InputAction.CallbackContext context);
        void OnUIShortCut5(InputAction.CallbackContext context);
        void OnUIShortCut4(InputAction.CallbackContext context);
        void OnUIShortCut3(InputAction.CallbackContext context);
        void OnUIShortCut2(InputAction.CallbackContext context);
        void OnUIShortCut1(InputAction.CallbackContext context);
    }
    public interface ICameraActions
    {
        void OnCameraXY(InputAction.CallbackContext context);
        void OnCameraZoom(InputAction.CallbackContext context);
    }
    public interface IMiscActions
    {
        void OnSpeedUp(InputAction.CallbackContext context);
    }
    public interface IMoveActions
    {
        void OnRoll(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
    }
    public interface IItemActions
    {
        void OnRBT(InputAction.CallbackContext context);
        void OnRBH(InputAction.CallbackContext context);
        void OnRTT(InputAction.CallbackContext context);
        void OnRTH(InputAction.CallbackContext context);
        void OnLBT(InputAction.CallbackContext context);
        void OnLBH(InputAction.CallbackContext context);
        void OnLTT(InputAction.CallbackContext context);
        void OnLTH(InputAction.CallbackContext context);
    }
}
